Provider secret special chars
SAP/crossplane-provider-btp pull request #53
Opened 2024-12-05 09:11 UTC by MarlenKoch

### Problem:

When the provider secret contains a special char (like "), the error message is the following: 
`cannot create new Service: failed to get BTP accounts service client.: invalid character '9' after object key:value pair`

https://github.com/SAP/crossplane-provider-btp/blob/main/btp/cisclient.go#L236-L254

### Solution:
This PR introduces a special error message in case the user credentials json can't be parsed. 

Since there are two different secrets, one of which already had a more specific error message, I added the new error message to the user credentials (and not the cis-provider-secret).

2024-12-12 12:01 UTC, sdischer-sap requested changes
Just one minor addition required. Other then that looks really good. Nice work!

2024-12-12 12:01 UTC, sdischer-sap commented on internal/clients/tfclient/tfclient.go
> +			return ps, errors.Wrap(err, errCouldNotParseUserCredential)
Just seeing that now sorry. 
There is actually another function called `TerraformSetupBuilder` above which does pretty much the same thing. 
Probably makes sense to combined those, but for now lets just add the same error message on parsing there like here.

I will create a follow up issue for adding test cases for that.

2024-12-17 07:08 UTC, sdischer-sap approved these changes
lgtm, thank you!

2024-12-18 16:59 UTC, maximiliantech approved these changes
Thanks for your contribution! 🚀

2024-12-18 17:03 UTC, merged